# Generated by Django 5.0 on 2024-07-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='our_story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_body', models.TextField()),
                ('main_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='our_vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_body', models.TextField()),
                ('main_body', models.TextField()),
            ],
        ),
    ]
