# Generated by Django 5.0 on 2024-07-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCH_Admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='our_vision',
            name='main_body',
        ),
    ]
