# Generated by Django 5.0 on 2024-07-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCH_Admin', '0002_remove_our_vision_main_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdCoffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('discount', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='Media')),
            ],
        ),
        migrations.CreateModel(
            name='HotCoffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='Media')),
            ],
        ),
    ]
