# Generated by Django 5.0 on 2024-07-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCH_Admin', '0003_coldcoffee_hotcoffee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coldcoffee',
            name='discount',
        ),
    ]
