# Generated by Django 5.0 on 2024-07-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCH_Admin', '0005_offer_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Table_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('person', models.IntegerField()),
            ],
        ),
    ]
